const dictionary: Record<string, string> = {
  "blog": "بلاگ",
  "summary": "خلاصہ",
  "This": "یہ",
  "is": "ہے",
  "a": "ایک",
  "sample": "نمونہ",
  "No content found.": "کوئی مواد نہیں ملا۔",
  "no": "کوئی",
  "content": "مواد",
  "found": "ملا",
  "post": "پوسٹ",
  "author": "مصنف",
  "date": "تاریخ",
  "comment": "تبصرہ",
  "read": "پڑھیں",
  "share": "بانٹیں",
  "title": "عنوان",
  "category": "زمرہ",
  "tags": "ٹیگز",
  "update": "اپ ڈیٹ",
  "publish": "اشاعت",
  "view": "دیکھیں",
  "like": "پسند کریں",
  "subscribe": "سبسکرائب",
  "article": "مضمون",
  "edit": "ترمیم",
  "save": "محفوظ کریں",
  "delete": "حذف کریں",
  "search": "تلاش",
  "home": "صفحہ اول",
  "page": "صفحہ",
  "link": "رابطہ",
  "tag": "ٹیگ",
  "description": "تفصیل",
  "readers": "قارئین",
  "followers": "پیروکار",
  "website": "ویب سائٹ",
  "posters": "پوسٹرز",
  "section": "حصہ",
  "feedback": "آراء",
  "message": "پیغام",
  "reply": "جواب",
  "notification": "اطلاع",
  "newsletter": "نیوز لیٹر",
  "social": "سماجی",
  "media": "میڈیا",
  "profile": "پروفائل",
  "login": "لاگ ان",
  "logout": "لاگ آؤٹ", "just": "بس",
  "over": "اوپر",
  "state": "ریاست",
  "year": "سال",
  "day": "دن",
  "into": "میں",
  "email": "ای میل",
  "two": "دو",
  "health": "صحت",
  "n": "ن",
  "world": "دنیا",
  "re": "دوبارہ",
  "next": "اگلا",
  "used": "استعمال کیا",
  "go": "جائیں",
  "b": "ب",
  "work": "کام",
  "last": "آخری",
  "most": "زیادہ تر",
  "products": "مصنوعات",
  "music": "موسیقی",
  "buy": "خریدیں",
  "data": "ڈیٹا",
  "make": "بنائیں",
  "them": "انہیں",
  "should": "چاہیے",
  "product": "مصنوع",
  "system": "نظام",
 
  "her": "اس کی",
  "city": "شہر",
  "t": "ٹ",
  "add": "شامل کریں",
  "policy": "پالیسی",
  "number": "نمبر",
  "such": "ایسا",
  "please": "براہ کرم",
  "available": "دستیاب",
  "copyright": "کاپی رائٹ",
  "support": "مدد",
 
  "after": "بعد",
  "best": "بہترین",
  "software": "سافٹ ویئر",
  "then": "پھر",
  "jan": "جنوری",
  "good": "اچھا",
  "video": "ویڈیو",
  "well": "بھی",
  "d": "ڈی",
  "where": "کہاں",
  "info": "معلومات",
  "rights": "حقوق",
  "public": "عوامی",
  "books": "کتابیں",
  "high": "اعلیٰ",
  "school": "اسکول",
  "through": "کے ذریعے",
  "m": "م",
  "each": "ہر",
  "links": "لنکس",
  "she": "وہ",
  "review": "جائزہ",
  "years": "سال",
  "order": "آرڈر",
  "very": "بہت",
  "privacy": "رازداری",
  "book": "کتاب",
  "items": "اشیاء",
  "company": "کمپنی",
  "r": "ر",
 
  "group": "گروپ",
  "need": "ضرورت",
  "many": "بہت سے",
  "user": "صارف",
  "said": "کہا",
  "de": "دی",
  "does": "کرتا ہے",
  "set": "سیٹ",
  "under": "تحت",
  "general": "عمومی",
  "research": "تحقیق",
  "university": "جامعہ",
  "january": "جنوری",
  "mail": "میل",
  "full": "مکمل",
  "map": "نقشہ",
  "reviews": "جائزے",
  "program": "پروگرام",
  "life": "زندگی",
  "know": "جانتے ہیں",
  "games": "کھیل",
  "way": "طریقہ",
  "days": "دن",
  "management": "انتظامیہ",
  "p": "پ",
  "part": "حصہ",
  "could": "سکتا تھا",
  "great": "زبردست",
  "united": "متحدہ",
  "hotel": "ہوٹل",
  "real": "حقیقی",
  "f": "ف",
  "item": "آئٹم",
  "international": "بین الاقوامی",
  "center": "مرکز",
  "ebay": "ای بے",
  "must": "ضروری",
  "store": "دکان",
  "travel": "سفر",
  "comments": "تبصرے",
  "made": "بنایا",
  "development": "ترقی",
  "report": "رپورٹ",
  "off": "بند",
  "member": "رکن",
  "details": "تفصیلات",
  "line": "لائن",
  "terms": "شرائط",
  "before": "اس سے پہلے",
  "hotels": "ہوٹل",
  "did": "کیا",
  "send": "بھیجیں",
  "right": "صحیح",
  "type": "قسم",
  "because": "کیونکہ",
  "local": "مقامی",
  "those": "وہ",
  "using": "استعمال",
  "results": "نتائج",
  "office": "دفتر",
  "education": "تعلیم",
  "national": "قومی",
  "car": "گاڑی",
  "design": "ڈیزائن",
  "take": "لیں",
  "posted": "پوسٹ کیا",
  "internet": "انٹرنیٹ",
  "address": "پتہ",
  "community": "برادری",
  "within": "کے اندر",
  "states": "ریاستیں",
  "area": "علاقہ",
  "want": "چاہتے ہیں",
  "phone": "فون",
  "dvd": "ڈی وی ڈی",
  "shipping": "شپنگ",
  "reserved": "محفوظ",
  "subject": "موضوع",
  "between": "کے درمیان",
  "forum": "فورم",
  "family": "خاندان",
  "l": "ل",
  "long": "لمبا",
  "based": "بنیاد",
  "w": "و",
  "code": "کوڈ",
  "show": "دکھائیں",
  "o": "او",
  "even": "یہاں تک کہ",
  "black": "کالا",
  "check": "چیک",
  "special": "خاص",
  "prices": "قیمتیں",
 
  "index": "انڈیکس",
  "being": "ہونا",
  "women": "عورتیں",
  "much": "بہت",
  "sign": "دستخط",
  "file": "فائل",
 
  "open": "کھولیں",
  "today": "آج",
  "technology": "ٹیکنالوجی",
  "south": "جنوب",
  "case": "کیس",
  "project": "منصوبہ",
  "same": "ایک ہی",
  "pages": "صفحات",
  "uk": "یو کے",
  "version": "ورژن",
  
  "own": "اپنا",
  
  "sports": "کھیل",
  "house": "گھر",
  "related": "متعلقہ",
  "security": "سلامتی",
  "both": "دونوں",
  "g": "گ",
  "county": "کاؤنٹی",
  "american": "امریکی",
  "photo": "تصویر",
  "game": "کھیل",
  "members": "ارکان",
  "power": "طاقت",
  "while": "جبکہ",
  "care": "دھیان",
  "network": "نیٹ ورک",
  "down": "نیچے",
  "computer": "کمپیوٹر",
  "systems": "نظام",
  "three": "تین",
  "total": "کل",
  "place": "جگہ",
  "end": "اختتام",
  "following": "مندرجہ ذیل",
  "download": "ڈاؤن لوڈ",
  "h": "ح",
  "him": "اسے",
  "without": "بغیر",
  "per": "فی",
  "access": "رسائی",
  "think": "سوچیں",
  "north": "شمال",
  "resources": "وسائل",
  "current": "موجودہ",
  "posts": "پوسٹ",
  "big": "بڑا",
  
  "law": "قانون",
  "control": "کنٹرول",
  "water": "پانی",
  "history": "تاریخ",
  "pictures": "تصاویر",
  "size": "سائز",
  "art": "فن",
  "personal": "ذاتی",
  "since": "جب سے",
  "including": "شامل ہے",
  "guide": "رہنما",
  "shop": "دکان",
  "directory": "ڈائریکٹری",
  "board": "بورڈ",
  "location": "مقام",
  "change": "تبدیلی",
  "white": "سفید",
  "text": "متن",
  "small": "چھوٹا",
  "rating": "درجہ بندی",
  "rate": "درجہ",
  "government": "حکومت",
  "children": "بچے",
  "during": "دوران",
  "usa": "یو ایس اے",
  "return": "واپس",
  "students": "طلباء",
  "v": "و",
  "shopping": "خریداری",
  "account": "اکاؤنٹ",
  "times": "بار",
  "sites": "سائٹس",
  "level": "سطح",
  "digital": "ڈیجیٹل",
  
  "previous": "پچھلا",
  "form": "فارم",
  "events": "تقریبات",
  "love": "محبت",
  "old": "پرانا",
  "john": "جان",
  "main": "مرکزی",
  "call": "کال",
  "hours": "گھنٹے",
  "image": "تصویر",
  "department": "محکمہ",
  "business": "کاروبار",
  "non": "غیر",
  "k": "ک",
  "y": "ی",
  "insurance": "انشورنس",
  "another": "دوسرا",
  "why": "کیوں",
  "shall": "چاہیے",
  "property": "جائیداد",
  "class": "کلاس",
  "cd": "سی ڈی",
  "still": "اب بھی",
  "money": "پیسہ",
  "quality": "معیار",
};

export function translateToUrdu(text: string): string {
  return text
    .split(" ")
    .map(word => dictionary[word] || word)
    .join(" ");
}

