const dictionary: Record<string, string> = {
  "blog": "بلاگ",
  "summary": "خلاصہ",
  "This": "یہ",
  "is": "ہے",
  "a": "ایک",
  "sample": "نمونہ",
  "No content found.": "کوئی مواد نہیں ملا۔",
  "no": "کوئی",
  "content": "مواد",
  "found": "ملا",
  "post": "پوسٹ",
  "author": "مصنف",
  "date": "تاریخ",
  "comment": "تبصرہ",
  "read": "پڑھیں",
  "share": "بانٹیں",
  "title": "عنوان",
  "category": "زمرہ",
  "tags": "ٹیگز",
  "update": "اپ ڈیٹ",
  "publish": "اشاعت",
  "view": "دیکھیں",
  "like": "پسند کریں",
  "subscribe": "سبسکرائب",
  "article": "مضمون",
  "edit": "ترمیم",
  "save": "محفوظ کریں",
  "delete": "حذف کریں",
  "search": "تلاش",
  "home": "صفحہ اول",
  "page": "صفحہ",
  "link": "رابطہ",
  "tag": "ٹیگ",
  "description": "تفصیل",
  "readers": "قارئین",
  "followers": "پیروکار",
  "website": "ویب سائٹ",
  "posters": "پوسٹرز",
  "section": "حصہ",
  "feedback": "آراء",
  "message": "پیغام",
  "reply": "جواب",
  "notification": "اطلاع",
  "newsletter": "نیوز لیٹر",
  "social": "سماجی",
  "media": "میڈیا",
  "profile": "پروفائل",
  "login": "لاگ ان",
  "logout": "لاگ آؤٹ", "just": "بس",
  "over": "اوپر",
  "state": "ریاست",
  "year": "سال",
  "day": "دن",
  "into": "میں",
  "email": "ای میل",
  "two": "دو",
  "health": "صحت",
  "n": "ن",
  "world": "دنیا",
  "re": "دوبارہ",
  "next": "اگلا",
  "used": "استعمال کیا",
  "go": "جائیں",
  "b": "ب",
  "work": "کام",
  "last": "آخری",
  "most": "زیادہ تر",
  "products": "مصنوعات",
  "music": "موسیقی",
  "buy": "خریدیں",
  "data": "ڈیٹا",
  "make": "بنائیں",
  "them": "انہیں",
  "should": "چاہیے",
  "product": "مصنوع",
  "system": "نظام",

  "her": "اس کی",
  "city": "شہر",
  "t": "ٹ",
  "add": "شامل کریں",
  "policy": "پالیسی",
  "number": "نمبر",
  "such": "ایسا",
  "please": "براہ کرم",
  "available": "دستیاب",
  "copyright": "کاپی رائٹ",
  "support": "مدد",

  "after": "بعد",
  "best": "بہترین",
  "software": "سافٹ ویئر",
  "then": "پھر",
  "jan": "جنوری",
  "good": "اچھا",
  "video": "ویڈیو",
  "well": "بھی",
  "d": "ڈی",
  "where": "کہاں",
  "info": "معلومات",
  "rights": "حقوق",
  "public": "عوامی",
  "books": "کتابیں",
  "high": "اعلیٰ",
  "school": "اسکول",
  "through": "کے ذریعے",
  "m": "م",
  "each": "ہر",
  "links": "لنکس",
  "she": "وہ",
  "review": "جائزہ",
  "years": "سال",
  "order": "آرڈر",
  "very": "بہت",
  "privacy": "رازداری",
  "book": "کتاب",
  "items": "اشیاء",
  "company": "کمپنی",
  "r": "ر",

  "group": "گروپ",
  "need": "ضرورت",
  "many": "بہت سے",
  "user": "صارف",
  "said": "کہا",
  "de": "دی",
  "does": "کرتا ہے",
  "set": "سیٹ",
  "under": "تحت",
  "general": "عمومی",
  "research": "تحقیق",
  "university": "جامعہ",
  "january": "جنوری",
  "mail": "میل",
  "full": "مکمل",
  "map": "نقشہ",
  "reviews": "جائزے",
  "program": "پروگرام",
  "life": "زندگی",
  "know": "جانتے ہیں",
  "games": "کھیل",
  "way": "طریقہ",
  "days": "دن",
  "management": "انتظامیہ",
  "p": "پ",
  "part": "حصہ",
  "could": "سکتا تھا",
  "great": "زبردست",
  "united": "متحدہ",
  "hotel": "ہوٹل",
  "real": "حقیقی",
  "f": "ف",
  "item": "آئٹم",
  "international": "بین الاقوامی",
  "center": "مرکز",
  "ebay": "ای بے",
  "must": "ضروری",
  "store": "دکان",
  "travel": "سفر",
  "comments": "تبصرے",
  "made": "بنایا",
  "development": "ترقی",
  "report": "رپورٹ",
  "off": "بند",
  "member": "رکن",
  "details": "تفصیلات",
  "line": "لائن",
  "terms": "شرائط",
  "before": "اس سے پہلے",
  "hotels": "ہوٹل",
  "did": "کیا",
  "send": "بھیجیں",
  "right": "صحیح",
  "type": "قسم",
  "because": "کیونکہ",
  "local": "مقامی",
  "those": "وہ",
  "using": "استعمال",
  "results": "نتائج",
  "office": "دفتر",
  "education": "تعلیم",
  "national": "قومی",
  "car": "گاڑی",
  "design": "ڈیزائن",
  "take": "لیں",
  "posted": "پوسٹ کیا",
  "internet": "انٹرنیٹ",
  "address": "پتہ",
  "community": "برادری",
  "within": "کے اندر",
  "states": "ریاستیں",
  "area": "علاقہ",
  "want": "چاہتے ہیں",
  "phone": "فون",
  "dvd": "ڈی وی ڈی",
  "shipping": "شپنگ",
  "reserved": "محفوظ",
  "subject": "موضوع",
  "between": "کے درمیان",
  "forum": "فورم",
  "family": "خاندان",
  "l": "ل",
  "long": "لمبا",
  "based": "بنیاد",
  "w": "و",
  "code": "کوڈ",
  "show": "دکھائیں",
  "o": "او",
  "even": "یہاں تک کہ",
  "black": "کالا",
  "check": "چیک",
  "special": "خاص",
  "prices": "قیمتیں",

  "index": "انڈیکس",
  "being": "ہونا",
  "women": "عورتیں",
  "much": "بہت",
  "sign": "دستخط",
  "file": "فائل",

  "open": "کھولیں",
  "today": "آج",
  "technology": "ٹیکنالوجی",
  "south": "جنوب",
  "case": "کیس",
  "project": "منصوبہ",
  "same": "ایک ہی",
  "pages": "صفحات",
  "uk": "یو کے",
  "version": "ورژن",

  "own": "اپنا",

  "sports": "کھیل",
  "house": "گھر",
  "related": "متعلقہ",
  "security": "سلامتی",
  "both": "دونوں",
  "g": "گ",
  "county": "کاؤنٹی",
  "american": "امریکی",
  "photo": "تصویر",
  "game": "کھیل",
  "members": "ارکان",
  "power": "طاقت",
  "while": "جبکہ",
  "care": "دھیان",
  "network": "نیٹ ورک",
  "down": "نیچے",
  "computer": "کمپیوٹر",
  "systems": "نظام",
  "three": "تین",
  "total": "کل",
  "place": "جگہ",
  "end": "اختتام",
  "following": "مندرجہ ذیل",
  "download": "ڈاؤن لوڈ",
  "h": "ح",
  "him": "اسے",
  "without": "بغیر",
  "per": "فی",
  "access": "رسائی",
  "think": "سوچیں",
  "north": "شمال",
  "resources": "وسائل",
  "current": "موجودہ",
  "posts": "پوسٹ",
  "big": "بڑا",

  "law": "قانون",
  "control": "کنٹرول",
  "water": "پانی",
  "history": "تاریخ",
  "pictures": "تصاویر",
  "size": "سائز",
  "art": "فن",
  "personal": "ذاتی",
  "since": "جب سے",
  "including": "شامل ہے",
  "guide": "رہنما",
  "shop": "دکان",
  "directory": "ڈائریکٹری",
  "board": "بورڈ",
  "location": "مقام",
  "change": "تبدیلی",
  "white": "سفید",
  "text": "متن",
  "small": "چھوٹا",
  "rating": "درجہ بندی",
  "rate": "درجہ",
  "government": "حکومت",
  "children": "بچے",
  "during": "دوران",
  "usa": "یو ایس اے",
  "return": "واپس",
  "students": "طلباء",
  "v": "و",
  "shopping": "خریداری",
  "account": "اکاؤنٹ",
  "times": "بار",
  "sites": "سائٹس",
  "level": "سطح",
  "digital": "ڈیجیٹل",

  "previous": "پچھلا",
  "form": "فارم",
  "events": "تقریبات",
  "love": "محبت",
  "old": "پرانا",
  "john": "جان",
  "main": "مرکزی",
  "call": "کال",
  "hours": "گھنٹے",
  "image": "تصویر",
  "department": "محکمہ",
  "business": "کاروبار",
  "non": "غیر",
  "k": "ک",
  "y": "ی",
  "insurance": "انشورنس",
  "another": "دوسرا",
  "why": "کیوں",
  "shall": "چاہیے",
  "property": "جائیداد",
  "class": "کلاس",
  "cd": "سی ڈی",
  "still": "اب بھی",
  "money": "پیسہ",
  "quality": "معیار",
  "every": "ہر",
  "listing": "فہرست",
  "country": "ملک",
  "private": "نجی",
  "little": "چھوٹا",
  "visit": "دورہ",

  "tools": "آلات",
  "low": "کم",

  "customer": "گاہک",
  "december": "دسمبر",
  "compare": "موازنہ کریں",
  "movies": "فلمیں",
  "include": "شامل کریں",
  "college": "کالج",
  "value": "قدر",
  "york": "یورک",
  "man": "مرد",
  "card": "کارڈ",
  "jobs": "نوکریاں",
  "provide": "فراہم کریں",
  "food": "خوراک",
  "source": "ذرائع",
  "different": "مختلف",
  "press": "صحافت",
  "learn": "سیکھیں",
  "sale": "فروخت",
  "around": "چاروں طرف",
  "print": "پرنٹ",
  "course": "کورس",
  "job": "نوکری",
  "canada": "کینیڈا",
  "process": "عمل",
  "teen": "نوعمر",
  "room": "کمرہ",
  "stock": "اسٹاک",
  "training": "تربیت",
  "too": "بھی",
  "credit": "کریڈٹ",
  "point": "نکتہ",
  "join": "شامل ہوں",
  "science": "سائنس",
  "men": "مرد",
  "categories": "زمرے",
  "advanced": "اعلی درجے کا",
  "west": "مغرب",
  "sales": "فروخت",
  "look": "دیکھیں",
  "english": "انگریزی",
  "left": "بائیں",
  "team": "ٹیم",
  "estate": "جائیداد",
  "box": "ڈبہ",
  "conditions": "شرائط",
  "select": "منتخب کریں",
  "windows": "ونڈوز",
  "photos": "تصاویر",
  "gay": "ہم جنس پرست",
  "thread": "تھریڈ",
  "week": "ہفتہ",

  "note": "نوٹ",
  "live": "براہ راست",
  "large": "بڑا",
  "gallery": "گیلری",
  "table": "میز",
  "register": "رجسٹر کریں",
  "however": "تاہم",
  "june": "جون",
  "october": "اکتوبر",
  "november": "نومبر",
  "market": "بازار",
  "library": "کتب خانہ",
  "really": "واقعی",
  "action": "عمل",
  "start": "شروع کریں",
  "series": "سیریز",
  "model": "ماڈل",
  "features": "خصوصیات",
  "air": "ہوا",
  "industry": "صنعت",
  "plan": "منصوبہ",
  "human": "انسان",
  "provided": "فراہم کیا گیا",
  "tv": "ٹی وی",
  "yes": "ہاں",
  "required": "ضروری",
  "second": "دوسرا",
  "hot": "گرم",
  "accessories": "لوازمات",
  "cost": "لاگت",
  "movie": "فلم",
  "forums": "فورمز",
  "march": "مارچ",
  "september": "ستمبر",
  "better": "بہتر",
  "say": "کہیں",
  "questions": "سوالات",
  "july": "جولائی",
  "yahoo": "یاہو",
  "going": "جانا",
  "medical": "طبی",
  "test": "ٹیسٹ",
  "friend": "دوست",
  "come": "آنا",
  "dec": "دسمبر",
  "server": "سرور",
  "pc": "پی سی",
  "study": "مطالعہ",
  "application": "درخواست",
  "cart": "ٹوکری",
  "staff": "عملہ",
  "articles": "مضامین",
  "san": "سان",

  "again": "دوبارہ",
  "play": "کھیلیں",
  "looking": "دیکھنا",
  "issues": "مسائل",
  "april": "اپریل",
  "never": "کبھی نہیں",
  "users": "صارفین",
  "complete": "مکمل",
  "street": "گلی",
  "topic": "موضوع",

  "financial": "مالی",
  "things": "چیزیں",
  "working": "کام کرنا",
  "against": "کے خلاف",
  "standard": "معیاری",
  "tax": "ٹیکس",
  "person": "شخص",
  "below": "نیچے",
  "mobile": "موبائل",
  "less": "کم",
  "got": "حاصل کیا",
  "party": "پارٹی",
  "payment": "ادائیگی",
  "equipment": "سامان",

  "student": "طالب علم",
  "let": "اجازت دیں",
  "programs": "پروگرام",
  "offers": "آفرز",
  "legal": "قانونی",
  "above": "اوپر",
  "recent": "حال ہی میں",
  "park": "پارک",
  "stores": "دکانیں",
  "side": "جانب",
  "act": "عمل کریں",
  "problem": "مسئلہ",
  "red": "سرخ",
  "give": "دیں",
  "memory": "یادداشت",
  "performance": "کارکردگی",

  "august": "اگست",
  "quote": "اقتباس",
  "language": "زبان",
  "story": "کہانی",
  "sell": "بیچیں",
  "options": "اختیارات",
  "experience": "تجربہ",
  "rates": "ریٹس",
  "create": "بنائیں",
  "key": "کلید",
  "body": "جسم",
  "young": "نوجوان",
  "america": "امریکہ",
  "important": "اہم",
  "field": "میدان",
  "few": "چند",
  "east": "مشرق",
  "paper": "کاغذ",
  "single": "اکیلا",
  "age": "عمر",
  "activities": "سرگرمیاں",
  "club": "کلب",
  "example": "مثال",
  "girls": "لڑکیاں",
  "additional": "اضافی",
  "password": "پاس ورڈ",
  "latest": "تازہ ترین",
  "something": "کچھ",
  "road": "سڑک",
  "gift": "تحفہ",
  "question": "سوال",
  "changes": "تبدیلیاں",
  "night": "رات",
  "hard": "مشکل",
  "texas": "ٹیکساس",
  "pay": "ادائیگی",
  "four": "چار",
  "poker": "پوکر",
  "status": "حیثیت",
  "browse": "براؤز کریں",
  "issue": "مسئلہ",
  "range": "حد",
  "building": "عمارت",
  "seller": "بیچنے والا",
  "court": "عدالت",
  "february": "فروری",
  "always": "ہمیشہ",
  "result": "نتیجہ",
  "audio": "آڈیو",
  "light": "روشنی",
  "write": "لکھیں",
  "war": "جنگ",
  "offer": "پیشکش",
  "blue": "نیلا",
  "groups": "گروپس",
  "easy": "آسان",
  "given": "دیا گیا",
  "files": "فائلز",
  "event": "واقعہ",
  "release": "ریلیز",
  "analysis": "تجزیہ",
  "request": "درخواست",
  "fax": "فیکس",
  "china": "چین",
  "making": "بنانا",
  "picture": "تصویر",
  "needs": "ضرورتیں",
  "possible": "ممکن",
  "might": "شاید",
  "professional": "پیشہ ور",
  "yet": "ابھی تک",
  "month": "مہینہ",
  "major": "اہم",
  "star": "ستارہ",
  "areas": "علاقے",
  "future": "مستقبل",
  "space": "خلا",
  "committee": "کمیٹی",
  "hand": "ہاتھ",
  "sun": "سورج",
  "cards": "کارڈز",
  "problems": "مسائل",
  "london": "لندن",
  "washington": "واشنگٹن",
  "meeting": "میٹنگ",
  "rss": "آر ایس ایس",
  "become": "بن جانا",
  "interest": "دلچسپی",
  "id": "شناخت",
  "child": "بچہ",
  "keep": "رکھیں",
  "enter": "داخل ہوں",
  "california": "کیلیفورنیا",

  "similar": "مشابه",
  "garden": "باغ",
  "schools": "اسکول",
  "million": "ملین",
  "added": "شامل کیا گیا",
  "reference": "حوالہ",
  "companies": "کمپنیاں",
  "listed": "فہرست میں شامل",
  "baby": "بچہ",
  "learning": "سیکھنا",
  "energy": "توانائی",
  "run": "چلائیں",
  "delivery": "ڈیلیوری",
  "net": "نیٹ",
  "popular": "مشہور",
  "term": "اصطلاح",
  "film": "فلم",
  "stories": "کہانیاں",
  "put": "رکھیں",
  "computers": "کمپیوٹرز",
  "journal": "جرنل",
  "reports": "رپورٹس",
  "co": "کمپنی",
  "try": "کوشش کریں",
  "welcome": "خوش آمدید",
  "central": "مرکزی",
  "images": "تصاویر",
  "president": "صدر",
  "notice": "نوٹس",
  "original": "اصل",
  "head": "سر",
  "radio": "ریڈیو",
  "until": "تک",
  "cell": "خلیہ",
  "color": "رنگ",
  "self": "خود",
  "council": "کونسل",
  "away": "دور",
  "includes": "شامل ہے",
  "track": "ٹریک",
  "australia": "آسٹریلیا",
  "discussion": "بحث",
  "archive": "محفوظ شدہ",
  "once": "ایک بار",
  "others": "دوسرے",
  "entertainment": "تفریح",
  "agreement": "معاہدہ",
  "format": "فارمیٹ",
  "least": "کم از کم",
  "society": "سماج",
  "months": "مہینے",
  "log": "لاگ",
  "safety": "حفاظت",
  "friends": "دوست",
  "sure": "یقیناً",
  "faq": "عمومی سوالات",
  "trade": "تجارت",
  "edition": "ایڈیشن",
  "cars": "گاڑیاں",
  "messages": "پیغامات",
  "marketing": "مارکیٹنگ",
  "tell": "بتائیں",
  "further": "مزید",
  "updated": "اپ ڈیٹ",
  "association": "ایسوسی ایشن",
  "able": "قابل",
  "having": "ہونا",
  "provides": "فراہم کرتا ہے",
  "david": "ڈیوڈ",
  "fun": "مزہ",
  "already": "پہلے ہی",
  "green": "سبز",
  "studies": "مطالعے",
  "close": "بند",
  "common": "عام",
  "drive": "ڈرائیو",
  "specific": "مخصوص",
  "several": "کئی",
  "gold": "سونا",
  "feb": "فروری",
  "living": "زندگی",
  "sep": "ستمبر",
  "collection": "مجموعہ",
  "called": "کہا جاتا ہے",
  "short": "مختصر",
  "arts": "فن",
  "lot": "کافی",
  "ask": "پوچھیں",
  "display": "ڈسپلے",
  "limited": "محدود",
  "powered": "چلا رہا ہے",
  "solutions": "حل",
  "means": "معنی",
  "director": "ڈائریکٹر",
  "daily": "روزانہ",
  "beach": "ساحل",
  "past": "ماضی",
  "natural": "قدرتی",
  "whether": "چاہے",
  "due": "مقررہ",
  "electronics": "الیکٹرانکس",
  "five": "پانچ",
  "upon": "پر",
  "period": "مدت",
  "planning": "منصوبہ بندی",
  "database": "ڈیٹا بیس",
  "says": "کہتا ہے",
  "official": "سرکاری",
  "weather": "موسم",
  "mar": "مارچ",
  "land": "زمین",
  "average": "اوسط",
  "done": "ہو چکا",
  "technical": "تکنیکی",
  "window": "کھڑکی",
  "france": "فرانس",
  "pro": "پیشہ ور",
  "region": "علاقہ",
  "island": "جزیرہ",
  "record": "ریکارڈ",
  "direct": "براہ راست",
  "microsoft": "مائیکروسافٹ",
  "conference": "کانفرنس",
  "environment": "ماحول",
  "records": "ریکارڈز",
  "district": "ضلع",
  "calendar": "کلینڈر",
  "costs": "اخراجات",
  "style": "انداز",
  "url": "یو آر ایل",
  "front": "سامنے",
  "statement": "بیان",

  "parts": "حصے",
  "aug": "اگست",
  "ever": "کبھی",
  "downloads": "ڈاؤن لوڈز",
  "early": "جلدی",
  "miles": "میل",
  "sound": "آواز",
  "resource": "وسیلہ",
  "present": "موجودہ",
  "applications": "درخواستیں",
  "either": "دونوں میں سے کوئی ایک",
  "ago": "پہلے",
  "document": "دستاویز",
  "word": "لفظ",
  "works": "کام کرتا ہے",
  "material": "مواد",
  "bill": "بل",
  "apr": "اپریل",
  "written": "لکھا ہوا",
  "talk": "بات کریں",
  "federal": "وفاقی",
  "hosting": "ہوسٹنگ",
  "rules": "قواعد",
  "final": "آخری",
  "adult": "بالغ",
  "tickets": "ٹکٹ",
  "thing": "چیز",
  "centre": "مرکز",
  "requirements": "ضروریات",
  "via": "کے ذریعے",
  "cheap": "سستا",
  "kids": "بچے",
  "finance": "مالیات",
  "true": "سچا",
  "minutes": "منٹ",
  "else": "ورنہ",
  "mark": "نشان",
  "third": "تیسرا",
  "rock": "چٹان",
  "gifts": "تحائف",
  "europe": "یورپ",
  "reading": "مطالعہ",
  "topics": "موضوعات",
  "bad": "برا",
  "individual": "انفرادی",
  "tips": "مشورے",
  "plus": "پلس",
  "auto": "خودکار",
  "cover": "کور",
  "usually": "عمومی طور پر",

  "together": "ایک ساتھ",
  "videos": "ویڈیوز",
  "percent": "فی صد",
  "fast": "تیز",
  "function": "فنکشن",
  "fact": "حقیقت",
  "unit": "یونٹ",
  "getting": "حاصل کرنا",
  "global": "عالمی",
  "tech": "ٹیکنالوجی",
  "meet": "ملیں",
  "far": "دور",
  "economic": "معاشی",
  "player": "کھلاڑی",
  "projects": "پروجیکٹس",
  "lyrics": "گانے کے بول",
  "often": "اکثر",

  "submit": "جمع کریں",
  "germany": "جرمنی",
  "amount": "رقم",
  "watch": "دیکھیں",
  "included": "شامل ہے",
  "feel": "محسوس کریں",
  "though": "اگرچہ",
  "bank": "بینک",
  "risk": "خطرہ",
  "thanks": "شکریہ",
  "everything": "ہر چیز",
  "deals": "معاہدے",
  "various": "مختلف",
  "words": "الفاظ",
  "linux": "لینکس",
  "production": "پیداوار",
  "commercial": "تجارتی",
  "james": "جیمز",
  "weight": "وزن",
  "town": "شہر",
  "heart": "دل",
  "advertising": "اشتہارات",
  "received": "موصول ہوا",
  "choose": "چنیں",
  "treatment": "علاج",

  "archives": "محفوظ شدہ دستاویزات",
  "points": "نقاط",
  "knowledge": "علم",
  "magazine": "میگزین",
  "error": "خرابی",
  "camera": "کیمرہ",
  "currently": "فی الحال",
  "construction": "تعمیرات",
  "toys": "کھلونے",
  "registered": "رجسٹرڈ",
  "clear": "صاف",
  "golf": "گالف",
  "receive": "حاصل کریں",
};

export function translateToUrdu(text: string): string {
  return text.toLocaleLowerCase()
    .split(" ")
    .map(word => dictionary[word] || word)
    .join(" ");
}

