const dictionary: Record<string, string> = {
  "read": "مطالعہ",
  "performance": "کارکردگی",
  "debugging": "ڈیبگنگ",
  "CSS": "سی ایس ایس",
  "JavaScript": "جاوا اسکرپٹ",
  "PDF": "پی ڈی ایف",
  "checklists": "چیک لسٹ",
  "guides": "رہنما",
  "core": "مرکزی",
  "web": "ویب",
  "vitals": "اہم اشاریے",
  "share": "شئیر کریں",
  "on": "پر",
  "Twitter": "ٹوئٹر",
  "LinkedIn": "لنکڈ اِن",
  "about": "کے بارے میں",
  "the": "یہ",
  "author": "مصنف",
  "loves": "محبت کرتا ہے",
  "beautiful": "خوبصورت",
  "content": "مواد",
  "doesn’t": "نہیں کرتا",
  "like": "پسند",
  "give": "دینا",
  "easily": "آسانی سے",
  "writing": "لکھنا",
  "most": "زیادہ تر",
  "probably": "شاید",
  "running": "چلا رہا ہوتا ہے",
  "front-end": "فرنٹ اینڈ",
  "UX": "یوزر ایکسپیرینس",
  "more": "مزید",
  "email": "ای میل",
  "newsletter": "نیوز لیٹر",
  "weekly": "ہفتہ وار",
  "tips": "مشورے",
  "trusted": "قابلِ اعتماد",
  "folks": "افراد",
  "unknowns": "نامعلوم عوامل",
  "impacting": "اثر انداز ہو رہے",
  "loading": "لوڈنگ",
  "network": "نیٹ ورک",
  "thermal": "تھرمل",
  "throttling": "تھراٹلنگ",
  "cache": "کیش",
  "eviction": "اخراج",
  "third-party": "تیسرے فریق",
  "scripts": "سکرپٹس",
  "parser": "پارسر",
  "blocking": "روکنا",
  "patterns": "پیٹرنز",
  "disk": "ڈسک",
  "I/O": "آئی/او",
  "IPC": "آئی پی سی",
  "latency": "تاخیر",
  "installed": "انسٹال شدہ",
  "extensions": "ایکسٹینشنز",
  "antivirus": "اینٹی وائرس",
  "software": "سافٹ ویئر",
  "firewalls": "فائر والز",
  "background": "پس منظر",
  "CPU": "سی پی یو",
  "tasks": "کام",
  "hardware": "ہارڈ ویئر",
  "memory": "میموری",
  "constraints": "پابندیاں",
  "differences": "فرق",
  "caching": "کیشنگ",
  "RTTS": "آر ٹی ٹی ایس",
  "cost": "لاگت",
  "experience": "تجربہ",
  "next": "اگلا",
  "fonts": "فونٹس",
  "rendering": "رینڈرنگ",
  "default": "ڈیفالٹ",
  "images": "تصاویر",
  "often": "اکثر",
  "consuming": "استعمال کرنا",
  "too": "زیادہ",
  "much": "بہت زیادہ",
  "talk": "تقریر",
  "Eleventy": "ایلیونٹی",
  "Alpine": "الپائن",
  "Tailwind": "ٹیل ونڈ",
  "towards": "کی طرف",
  "lightweight": "ہلکا پھلکا",
  "Jamstack": "جیم اسٹیک",
  "Nicola": "نکولا",
  "Goutay": "گوٹے",
  "explains": "وضاحت کرتا ہے",
  "shows": "دکھاتا ہے",
  "use": "استعمال",
  "approach": "طریقہ",
  "along": "کے ساتھ",
  "GitHub": "گٹ ہب",
  "repo": "ریپو",
  "practice": "عملی طور پر",
  "CSR": "سی ایس آر",
  "SSR": "ایس ایس آر",
  "everything-in-between": "درمیانی سب کچھ",
  "min": "منٹ",
  "authorvitaly": "مصنف وٹالی",
  "friedman": "فریڈمین",
  "and": "اور",
  "to": "کے لیے",
  "in": "میں",
  "when": "جب",
  "he": "وہ",
  "is": "ہے",
  "not": "نہیں",
  "he’s": "وہ ہے",
  "smashing": "زبردست",
  "by": "کی طرف سے",
  "with": "کے ساتھ",
  "so": "اتنا",
  "many": "کئی",
  "has": "ہے",
  "of": "کا",
  "his": "اس کی",
  "between": "کے درمیان",
  "how": "کیسے",
  "that": "جو",
  "ux.": "یوزر ایکسپیرینس۔",
  "ux": "یوزر ایکسپیرینس",
  "email.": "ای میل۔",
};

// export function translateToUrdu(text: string): string {
//   return text.toLocaleLowerCase()
//     .split(" ")
//     .map(word => dictionary[word] || word)
//     .join(" ");
// }

export function translateToUrdu(text: string): string {
  return text
    .split(" ")
    .map(word => {
      const cleanWord = word.toLowerCase().replace(/[^a-z0-9\-\/]+/gi, ""); // Remove punctuation
      const translated = dictionary[cleanWord] || cleanWord;
      return word.match(/[^\w\s]+$/) ? translated + word.match(/[^\w\s]+$/) : translated;
    })
    .join(" ");
}

